spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: *
    url: jdbc:mysql://localhost:3306/local

logging:
  level:
    com.baomidou.mybatisplus.samples.mysql: debug

server:
  port: 8080
